In [23]:
# KNN实现病例分析
# 数据读入
import pandas as pd
import numpy as np
import os

print(os.getcwd())

/Users/haifeng/coding/PycharmProjects/Machine-Learning/Class/multiple_regression

In [24]:
bc_data = pd.read_csv('bc_data.csv', header=0, nrows=500)
bc_data.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [25]:
# 数据理解
bc_data.shape

(500, 32)

In [26]:
print(bc_data.columns)

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave_points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [27]:
bc_data.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
count,5.000000e+02,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,...,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,3.263049e+07,14.224206,19.086320,92.606620,662.844800,0.095978,0.103948,0.089941,0.049446,0.181370,...,16.421980,25.508500,108.258320,896.003200,0.131972,0.256324,0.276420,0.115980,0.292212,0.083778
std,1.326933e+08,3.476809,4.164842,23.983476,349.357241,0.013666,0.053096,0.080259,0.038875,0.027716,...,4.806458,6.063133,33.312706,571.074422,0.022739,0.159147,0.209012,0.065896,0.063366,0.018108
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.062510,0.019380,0.000000,0.000000,0.116700,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,8.667040e+05,11.807500,16.070000,75.995000,430.550000,0.085992,0.063622,0.028885,0.020245,0.161875,...,13.097500,21.017500,84.567500,522.600000,0.116200,0.145925,0.114475,0.063302,0.251700,0.071270
50%,9.014320e+05,13.435000,18.680000,86.735000,556.150000,0.095825,0.091280,0.064315,0.033870,0.179550,...,14.985000,25.240000,97.980000,691.750000,0.131250,0.214850,0.231400,0.100650,0.283100,0.079900
75%,8.910808e+06,16.115000,21.562500,106.225000,800.775000,0.105100,0.130500,0.132150,0.074928,0.195625,...,19.265000,29.350000,127.150000,1150.750000,0.146000,0.343525,0.389450,0.166850,0.320050,0.092065
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.144700,0.345400,0.426800,0.201200,0.304000,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [28]:
bc_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       500 non-null    int64
 1   diagnosis                500 non-null    object
 2   radius_mean              500 non-null    float64
 3   texture_mean             500 non-null    float64
 4   perimeter_mean           500 non-null    float64
 5   area_mean                500 non-null    float64
 6   smoothness_mean          500 non-null    float64
 7   compactness_mean         500 non-null    float64
 8   concavity_mean           500 non-null    float64
 9   concave points_mean      500 non-null    float64
 10  symmetry_mean            500 non-null    float64
 11  fractal_dimension_mean   500 non-null    float64
 12  radius_se                500 non-null    float64
 13  texture_se               500 non-null    float64
 14  perimeter_se             500 non-null    float64
 15  area_se                  500 non-null    float64
 16  smoothness_se            500 non-null    float64
 17  compactness_se           500 non-null    float64
 18  concavity_se             500 non-null    float64
 19  concave points_se        500 non-null    float64
 20  symmetry_se              500 non-null    float64
 21  fractal_dimension_se     500 non-null    float64
 22  radius_worst             500 non-null    float64
 23  texture_worst            500 non-null    float64
 24  perimeter_worst          500 non-null    float64
 25  area_worst               500 non-null    float64
 26  smoothness_worst         500 non-null    float64
 27  compactness_worst        500 non-null    float64
 28  concavity_worst          500 non-null    float64
 29  concave_points_worst     500 non-null    float64
 30  symmetry_worst           500 non-null    float64
 31  fractal_dimension_worst  500 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 125.1+ KB

In [29]:
# 数据准备
data = bc_data.drop(['id'], axis=1)

print(data.head(2))

  diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38           122.8     1001.0
1         M        20.57         17.77           132.9     1326.0

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710
1          0.08474           0.07864          0.0869              0.07017

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33            184.6
1         0.1812  ...         24.99          23.41            158.8

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119
1      1956.0            0.1238             0.1866           0.2416

   concave_points_worst  symmetry_worst  fractal_dimension_worst
0                0.2654          0.4601                  0.11890
1                0.1860          0.2750                  0.08902

[2 rows x 31 columns]

In [30]:
data = bc_data.drop(['id'], axis=1)
X_data = data.drop(['diagnosis'], axis=1)
X_data.head(2)

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.8,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902

In [31]:
from sklearn.preprocessing import StandardScaler
means_normalization = StandardScaler()
means_normalization.fit(X_data)
X_data = means_normalization.transform(X_data)
X_data[2]

array([ 1.57364645,  0.52003097,  1.56069242,  1.54768845,  0.99772368,
        1.05485546,  1.34025106,  2.0201288 ,  0.92205337, -0.36549235,
        1.19195057, -0.76836312,  0.82270894,  1.13410154, -0.26634014,
        0.78591367,  0.19706816,  1.41619199,  0.21587279,  0.29485142,
        1.48865928,  0.00354957,  1.32940232,  1.42505247,  0.54708327,
        1.0577897 ,  0.83322363,  1.92950578,  1.09139277,  0.21018141])

In [32]:
y_data = np.ravel(data['diagnosis'])
y_data[0:6]

array(['M', 'M', 'M', 'M', 'M', 'M'], dtype=object)

In [33]:
from sklearn.model_selection import train_test_split
X_trainingSet, X_testSet, y_trainingSet, y_testSet = train_test_split(X_data, y_data,random_state=1, test_size=0.25)

print(X_trainingSet.shape)
print(X_testSet.shape)

(375, 30)
(125, 30)

In [34]:
# 算法选择及其超级参数的设置
from sklearn.neighbors import KNeighborsClassifier
myModel = KNeighborsClassifier(algorithm = 'kd_tree')

In [35]:
# 具体模型的训练
myModel.fit(X_trainingSet, y_trainingSet)

KNeighborsClassifier(algorithm='kd_tree')

In [36]:
myModel.get_params()

{'algorithm': 'kd_tree',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [37]:
# 用模型进行预测
y_predictSet = myModel.predict(X_testSet)
print(y_predictSet)
print(y_testSet)

['B' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'B'
 'B' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B'
 'M' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B'
 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'M' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'B'
 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B'
 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'B'
 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'M']
['B' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'B'
 'B' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B'
 'M' 'M' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B'
 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B'
 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B'
 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'B'
 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M']

In [38]:
# 模型评价
from sklearn.metrics import accuracy_score
print(accuracy_score(y_testSet, y_predictSet))

0.96